Feature/storage
ab180/saby pull request #2
Opened 2022-09-30 07:54 UTC by minjae999

초안 작성합니다. 리뷰 부탁드려요.

2022-10-05 04:18 UTC, 0xWOF requested changes

2022-10-05 04:18 UTC, 0xWOF commented on Source/AppleStorage/Protocol/AnyArrayStorage.swift
> +    public func get(key: Value.Key) -> Value? {
nice catch 입니다. 잡아주셔서 감사합니다.

2022-10-05 04:18 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +public class CoreDataArrayStorage<Item>: ArrayStorage
이런 형식은 어떨까요? 의견 부탁드립니다.

```swift
public class CoreDataArrayStorage<Item>: ArrayStorage where
    Item: (
        KeyIdentifiable
        & NSManagedObject
        & ManagedObjectUpdater
    )
{
```

참고: https://github.com/ab180/saby/blob/d80688802d0c2cb8aa5da34b393e97d30bb7bb92/Source/ESCArchitecture/Implement/Service/AnyService.swift#L24-L26

2022-10-05 04:18 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    public func save() throws {
save, rollback 은 CoreDataArrayStorage 를 사용함에 있어서 필수적인 함수인가요? ArrayStorage Protocol 만으로 CoreDataArrayStorage 을 완전히 사용할 수 없는것은 아닌가요? 실제 사용시에 AnyArrayStorage 타입으로 CoreDataArrayStorage 를 받아서 사용할 것으로 예상하는데, 이 경우 save, rollback 함수가 필수라면 문제가 될 수 있을 것 같습니다.

2022-10-05 04:18 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +public protocol ManagedObjectUpdater {
언제 필요로 하는 프로토콜인가요?

2022-10-05 04:18 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    public func push(_ value: Item) {
프로토콜 자체에서 throws 하는게 나을까요? 고민되는 부분이네요... 민재님 의견은 어떠신가요?

2022-10-05 04:18 UTC, 0xWOF commented on Test/AppleStorage/CoreDataArrayStorage.swift
> +        // Append
기능별로 test 함수를 분리하면 더 좋을 것 같습니다. 테스트 실패시에 어떤 테스트가 실패했는지 더 빨리, 더 자세히 알기 위해서요. 지금 형태로는 상위 테스트가 먼저 실패하면 하위 테스트가 진행되지 않을 것 같습니다.

2022-10-05 04:18 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    // MARK: -
지금 Saby 에서는 member, init 만 class 선언에 포함하고, 나머지 method 는 카테고리 별로 분류해서 extension 으로 선언하고 있습니다. 컨벤션이 괜찮다고 생각하시면 그것대로 수정 부탁드리고, 아니라면 민재님 의견을 공유해주세요!

참고: https://github.com/ab180/saby/blob/main/Source/Concurrency/Promise/Promise.swift

2022-10-05 04:18 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +public class CoreDataArrayStorage<Item>: ArrayStorage
`public final class` 로 선언해주셔도 무방해보입니다. 지금 Saby 컨벤션(문서화필요)으로는 어쩔 수 없는 경우를 제외하고 기본적으로 `final class` 를 사용하고 있습니다.

2022-10-05 05:48 UTC, minjae999 commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +public protocol ManagedObjectUpdater {
save, rollback해서 이하에 같이 설명됩니다.
redirect: https://github.com/ab180/saby/pull/2/files/87b084f918011b65e9027cd41334e05ec7745dee#r987520822

2022-10-05 05:50 UTC, minjae999 commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    // MARK: -
말씀한 컨벤션이 좋아보입니다. 제 의견도 동일합니다. class에서는 위에서 언급한, `member`, `init`만 선언에 포함하고 사용처에 따라서 extension에 빼겠습니다.

2022-10-05 05:50 UTC, minjae999 commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    public func push(_ value: Item) {
저는 Library에서 `Exception`을 먹으면 안된다고 생각합니다. `thorws`로 교체하는게 맞아보입니다.

2022-10-05 05:51 UTC, minjae999 commented on Test/AppleStorage/CoreDataArrayStorage.swift
> +        // Append
해당 부분은 고려하고 있습니다. 위의 Library 완성도가 높아지면 일괄 분리해서 Commit 하나 올리겠습니다.

2022-10-05 06:02 UTC, minjae999 commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    public func save() throws {
CoreData는 Save를 해주지 않는이상 반영되지 않습니다. 따라서 `Save`를 할 것인지 `Rollback`을 할 것인지 알려주어야 합니다. 만약 해당 기능을 추가하지 않는다면, 해당 `Class`에 Save를 관리하는 `Scheduler`를 두어야 합니다. 

또한 위 `Git Conversation`에서 언급한 `ManagedObjectUpdater`의 프로토콜은 CoreData의 Model을 직접 생성 할 수 없기에 Mock을 만들어 생성한곳에 업데이트 하기 위한것입니다. 해당 [링크](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/CreatingObjects.html#//apple_ref/doc/uid/TP40001075-CH5-SW1)를 보시면 `EmployeeMO `의 객체는 `Context`에 의해 `ManagedObject`가 만들어지고 난 뒤에 Data를 Write하게 되어있습니다.  

제가 원하는 Workflow는 다음과 같습니다.
1. `MockContext`에 의해  `MockDataModel`이 생성된다.
2. `MockDataModel`을 `Push`한다.
3. `Push`에서 **Updater의 Protocol**에 의해서 값이 저장된다. (옮겨가도록)

3번에서 값이 저장되는 Updater는 [여기](https://github.com/ab180/saby/pull/2/files#diff-56ec4c9d7e0b4b2a8be6d2462902de9f1e60be9be4eb216e92577ddaa7d24186)에 구현되어 있습니다. NSCopying 비슷하게 구현되면 됩니다. 

말씀하신 AnyArrayStorage타입때문에 저도 고민되었습니다. 안쪽에 데이터를 저장하는 스케줄러를 두는게 좋을까요? 
Combine을 사용하여 구현했을 땐, n초 `Timer`와 Save할 `DataCount`를 Merge해서 트리거를 발생시켜 Save를 자동화시켰습니다.

혹시라도 좋은 의견이 있다면 말씀 주세요.

2022-10-05 08:47 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    public func save() throws {
ArrayStorage 에 save 함수를 추가하고, Promise 를 리턴하도록 구두로 합의

2022-10-05 08:47 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    public func push(_ value: Item) {
https://github.com/ab180/saby/pull/2#discussion_r987682450

2022-10-05 08:49 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +public protocol ManagedObjectUpdater {
https://github.com/ab180/saby/pull/2#discussion_r987682450

2022-10-06 07:23 UTC, minjae999 commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +                    self.cachedItems = try self.getAll()
저장되고나서 캐시아이템을 업데이트 합니다.
저장 전까지는 캐싱된 데이터로 사용됩니다.

2022-10-06 07:24 UTC, minjae999 commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    private var filterdItems: [Item] {
해당 Getter의 Overhead가 살짝 우려되는데, 어떻게 생각하시나요?

2022-10-06 07:25 UTC, minjae999 commented on Test/AppleStorage/CoreDataArrayStorage.swift
> +}
구도가 잡히면 다양한 케이스를 추가 해 볼 예정입니다.

2022-10-06 07:42 UTC, minjae999 commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    private lazy var cachedItems: Atomic<[Item]> = Atomic((try? getAll()) ?? [])
데이터 집어넣을땐 mutate, get할땐 capture구현

2022-10-06 15:38 UTC, 0xWOF requested changes
부탁드립니다!

2022-10-06 15:38 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +        getAll().first { $0.key == key }
이거 fetchRequest 를 활용해서는 불가능한가요? 전체쿼리 => 필터하면 불필요하게 많은 데이터에 접근해야 할 것 같아서요.

2022-10-06 15:38 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    static func creator<O>() -> (NSManagedObjectContext) -> O? {
nil 이 리턴되는 경우는 언제인가요?

2022-10-06 15:38 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +public final class CoreDataArrayStorage<Item>  where
CoreDataArrayStorage 의 함수들은 thread safe 한가요? 클래스에서 지원하는 것이 좋다고 생각합니다.

2022-10-06 15:38 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    }
모든 배열 write 가 atomic 하지 않으면 크래시가 될 수도 있다고 알고 있어서 처리되는 것이 좋을 듯 합니다.

2022-10-06 15:38 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +        case .count(let uInt):
uInt 가 limit 이 되는 것이 어떨까요?

2022-10-06 15:38 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +            (uInt >= filterdItems.count) ? (maxCount = filterdItems.count) : (maxCount = Int(uInt))
max 함수로 더 간단히 처리가 가능할 듯 합니다.

2022-10-06 15:38 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +
배열들이 thread safe 하기위해 Lock 처리 또는 Atomic 처리가 필요해보입니다. Single Thread Operation Queue 로 처리하셔도 좋고, SabyConcurrency 의 Lock 이나, Atomic 을 활용해주셔도 좋습니다.

ps. call 횟수가 적어서 큰 차이는 없겠지만, ios lock api benchmark 관련 자료입니다. SabyConcurrency 는 Mutex 를 사용해서 구현되어 있습니다. (https://www.vadimbulavin.com/benchmarking-locking-apis/)

2022-10-06 15:39 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    private lazy var cachedItems: Atomic<[Item]> = Atomic((try? getAll()) ?? [])
👍

2022-10-06 15:39 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +
되어있네요. ㅋㅋㅋ

2022-10-06 15:40 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    private lazy var cachedItems: Atomic<[Item]> = Atomic((try? getAll()) ?? [])
참고: capture 는 value type 에 대해서만 (복사해서) 안전하고, reference type 에 대해서는 안전하지 않습니다.

2022-10-06 15:44 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    private var filterdItems: [Item] {
이 부분 때문에 "작업중인 배열" 하나만 관리해도 될 것 같습니다. 굳이 삭제 배열을 따로 관리안하고 cacheItems 에서 바로 값을 지워도 문제없지 않나...? 생각합니다.

2022-10-06 15:45 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    public init(directoryName: String = "saby.storage") {
default 를 제공하지 않는것이 실수의 여지를 줄여줄 것 같습니다.

2022-10-06 15:46 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    private let directoryName: String
왜 dictionaryName 인가요? FileArrayStorage 클래스여서 의아합니다. fileName 은 어떨까요?

2022-10-06 15:49 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    public func save() -> SabyConcurrency.Promise<Void> {
Module 명이 생략되어 되지 않을까 생각합니다. 어떻게 생각하시나요?

2022-10-07 03:14 UTC, minjae999 commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    private var filterdItems: [Item] {
그럼 나중에 두가지 방법을 일단 고려 해 보겠습니다.
1. Delete을 더 많이 사용할 경우. (get:key 와 get:limit)
2. Get을 더 많이 사용할 경우. 

1번일 경우에는 제가 구현한 방법을 홀드하고, 
2번일 경우에는 말씀하신 작업중 배열 하나만 관리하면 됩니다. 

push와 delete의 잦은 사용으로 인해서 atomic을 사용하고 있다는 부분도 고려 해야 할 것 같아요. 

일단은 말씀하신대로 **작업중인 배열 하나만 써보도록 하고** 실제 2.0 사용하면서, 사용하는 부분을 확인하고 거기에 맞춰 원복하던지 유지하던지 해볼게요.

2022-10-07 03:17 UTC, minjae999 commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +            guard nil == error else { fatalError() }
내부 콜백함수입니다. init시에 완료 콜백을 받자는 말씀일까요? 저도 그부분은 고려를 했습니다.

2022-10-07 03:23 UTC, minjae999 commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    static func creator<O>() -> (NSManagedObjectContext) -> O? {
수정하겠습니다. 바로 밑줄 Entity가 존재하지 않을경우 nil입니다. 
근데 그럴경우에 push시에 return되어 사용자가 모를텐데 이를 오쩌죠. 쓰로우라도 낼릴까요?

2022-10-07 03:29 UTC, minjae999 commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +    private let directoryName: String
dictoryName으로 한번 감쌉니다. 파일이름은 다음과 같이 명명됩니다. Library document 의 root안에 두고싶지 않아서 directory name으로 한번 감싸게 됩니다. 그래서 default인자를 둔 것이기도 합니다. (default file storage directory)

Default file storage directory
    - Abcd(`Abcd` Type Array Files)
    - Efgh(`Efgh` Type Array Files)
    - ...


```swift
let urls = manager.urls(for: .libraryDirectory, in: .userDomainMask)

var result = urls[0].appendingPathComponent(directoryName)
result.appendingPathComponent(String(describing: Item.self))
```

2022-10-11 07:28 UTC, minjae999 commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +        getAll().first { $0.key == key }
ok 변경완료

2022-10-11 07:33 UTC, minjae999 commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +        return Promise<Void>(on: .main) { resolve, reject in
순서를 보장을 위해 Block을 내부에서 사용합니다.
try를 그대로 유지했습니다. init을 제거했습니다.

2022-10-12 08:41 UTC, 0xWOF requested changes
구두 내용:
- CoreData:
    - ManagedObject 를 background thread 화
    - Protocol 에서 Promise 리턴하도록
    - init 함수 없애고 static 이 Promise 리턴하도록
- Array:
    - Operation 제거
    - save Lock 처리

2022-11-10 01:03 UTC, closed without merging