Feature/logger
ab180/saby pull request #3
Opened 2022-10-04 08:15 UTC by enebin

## 개요
- Logger 구현

## 기능 및 예시코드
- Writing...

## 테스트
- 테스트 코드 작성(`LoggerTest.swift`)

2022-10-05 09:02 UTC, 0xWOF requested changes

2022-10-05 09:02 UTC, 0xWOF commented on Source/AppleLogger/Logger+Extension.swift
> +//
현재 Saby 컨벤션으로는 `ObjectCategory` 형식으로 extension 파일이름을 정하려고 하고 있습니다. 물론 `Object+Category` 가 Objective C 때 부터 내려온 유서깊은 전통이라는 것은 인지하고 있으나... 굳이 얻는 이익 없다고 생각합니다. (`+` 를 안쓰는 이유는 파일명 더블클릭했을 때 파일명 전체가 선택안되는게 빡쳐서... ㅋㅋ...) 의견 부탁드립니다! cc. @minjae999

참고: https://github.com/ab180/saby/blob/main/Source/Concurrency/Contract/Chain/ContractThen.swift

2022-10-05 09:02 UTC, 0xWOF commented on Source/AppleLogger/LoggerConfiguration.swift
> +public struct LoggerConfiguration {
이런 경우에는 Logger.Configuration 으로 Nested 하게 정의하시는건 어떠신가요?

2022-10-06 02:44 UTC, enebin commented on Source/AppleLogger/LogLevel.swift
> +    /// debug
OSLog를 래핑해서 애플의 Unified logging system을 준수한다 뭐 이런 의미였는데 사실 크게 중요한 내용은 아닙니다 🤔

2022-10-06 02:49 UTC, enebin commented on Source/AppleLogger/Logger.swift
> +public class Logger {
굳이 오버라이드 시킬 일 없다면 보기 깔끔해서 좋은 것 같아요. 변경하겠습니다!

근데 저 같은 경우 `extension`을 다른 파일로 분리했는데 이거에 관한 컨벤션이 있을까요?
+) 일단은 예시처럼 분류별로 `extension`을 하나씩 줬는데(ex. `var`(computed), `func` ... ) 피드백 부탁드립니다.

2022-10-06 02:59 UTC, enebin commented on Source/AppleLogger/LogLevel.swift
> +    /// debug
아 그리고 이것도 여담인데 코멘트 영어로 쓰는게 맞나요 한글로 쓰는게 맞나요ㅋㅋㅋ 뭔가 글로벌한 오픈소스를 노리는 것 같아서 일단 영어로 쓰긴 했습니다만.. iOS SDK도 영어로 썼던 것 같고

2022-10-06 03:23 UTC, enebin commented on Source/AppleLogger/LoggerConfiguration.swift
> +public struct LoggerConfiguration {
후에 refactor나 검색을 이용할 때 `Configuration`이라는 이름을 가진 객체가 여러개 등장해 혼선을 빚을 수도 있지 않을까요??

예시를 든다면,
Logger 내에서 
``` Swift
class Logger {
    var configuration: Configuration
}
```
OtherClass 에서
``` Swift
class OhterClass {
    var configuration: Configuration
}
```
등으로 선언되는 경우가 있을 것 같습니다. `Logger.Configuration`처럼 명시적으로 사용한다는 등의 컨벤션이 동반되면 좋을 것 같다는 생각도 듭니다.
물론 기우일 수도 있구요..ㅎ

2022-10-06 03:48 UTC, 0xWOF commented on Source/AppleLogger/LogLevel.swift
> +    /// debug
영어로 작성해주시면 됩니다. 그리고 12 ~ 13 라인이 궁금했다기 보다 15 라인에서 debug 한줄만 있는것이 조금 의아했습니다.

2022-10-06 03:54 UTC, 0xWOF commented on Source/AppleLogger/LoggerConfiguration.swift
> +public struct LoggerConfiguration {
이 경우에는 Nested Class 로 선언하면 OtherClass 에서 Logger.Configuration 을 안하면 컴파일에러가 발생할 겁니다. 물론 같은 키워드가 위치에 따라서 다른 타입을 나타낸다는것을 문제삼으시는 것이라면 맞는 말씀이지만요. 
> 타입을 Logger.Configuration처럼 명시적으로 선언한다는 등의 컨벤션이 동반되면 좋을 것 같다는 생각도 드네요.
이 의견은 Logger class 내에서도 Logger.Configuration 로 표기하자는 말씀이신거죠?

일단은 public nested class 의 경우 모두 표기하도록, 나머지 nested class 의 경우 그러지 않아도 되도록 컨벤션을 잡는것으로 괜찮다고 봅니다.
참고: https://github.com/ab180/saby/blob/a7c0379bf487820fc2aeb229f72c5f721983fd80/Source/Concurrency/Promise/Promise.swift#L146

마지막으로 다른 곳에서 이미 `Setting` 이라는 명칭을 사용해서 여기서 통일하는 것이 어떨까 합니다!

2022-10-06 03:55 UTC, 0xWOF commented on Source/AppleLogger/Logger.swift
> +public class Logger {
https://github.com/ab180/saby/blob/main/Source/Concurrency/Promise/Promise.swift

이 파일 참고 해주시면 어떤 이야기인지 감이 오실것이라고 생각합니다!

2022-10-06 04:08 UTC, enebin commented on Source/AppleLogger/LogLevel.swift
> +    /// debug
아 그거 찐빠입니다. 고칠게요ㅋㅋㅋㅋ

2022-10-07 10:00 UTC, 0xWOF requested changes

2022-10-07 10:00 UTC, 0xWOF commented on Source/AppleLogger/LogLevel.swift
> +    func isHigherOrEqual(to level: LogLevel) -> Bool {
그냥 이 함수를 안쓰고 `>=` 를 써도 되는 것 아닌가요?

2022-10-07 10:00 UTC, 0xWOF commented on Source/AppleLogger/Logger.swift
> +    public init(configuration: Setting) {
문구 변경이 필요해보입니다.

2022-10-07 10:00 UTC, 0xWOF commented on Source/AppleLogger/LoggerExtension.swift
> +    public var configuration: Setting {
변수명 변경이 필요해보입니다.

2022-10-07 10:00 UTC, 0xWOF commented on Source/AppleLogger/LoggerExtension.swift
> +extension Logger {
코드가 그다지 길지 않아서 Logger.swift 에 포함되어도 될 것 같습니다.

2022-10-07 10:00 UTC, 0xWOF commented on Source/AppleLogger/LogService.swift
> +    func log(_ message: StaticString, log: OSLog?, type: OSLogType, _ args: CVarArg)
Logger 의 init 에서 subsystem 과 category 를 필수값으로 만들어서 OSLog? 를 OSLog 로 만드는게 어떨까요?

2022-10-07 10:00 UTC, 0xWOF commented on Source/AppleLogger/LogService.swift
> +    func log(_ message: StaticString, log: OSLog?, type: OSLogType, _ args: CVarArg)
subsystem 과 category 를 정하지 않으면 Logger 를 쓸 수 없다는 느낌으로?

2022-10-12 06:45 UTC, enebin commented on Source/AppleLogger/LogLevel.swift
> +    func isHigherOrEqual(to level: LogLevel) -> Bool {
값이 Int라는 걸 알고 있는 상태면 크게 어색하지 않은데 그렇지 않으면 레벨 사이에 상하관계가 불분명해지는 면이 있어서 가독성을 위해 새로운 함수로 래핑했습니다.

2022-10-12 08:02 UTC, 0xWOF commented on Source/AppleLogger/LoggerExtension.swift
> +    public var setting: Setting {
굳이 사용자에게 setting 주지 않아도 될 것 같습니다.

2022-10-12 08:04 UTC, 0xWOF commented on Source/AppleLogger/LoggerExtension.swift
> +    public func configure(with setting: Setting) {
동일하게 setting 을 init 이후 변경할 수 없게 하는게 좋다고 생각합니다.

2022-10-12 08:05 UTC, 0xWOF commented on Source/AppleLogger/Logger.swift
> +@available(iOS 10.0, *)
모든 코드가 암시적으로 iOS 11+ 여서 굳이 필요 없을 것 같습니다.

2022-10-12 08:06 UTC, 0xWOF commented on Source/AppleLogger/Setting.swift
> +        var osLog: OSLog?
다른 comment 가 해결되면 이 OSLog 가 non null type 으로 처리가 가능할 것 같습니다.

2022-10-12 08:07 UTC, 0xWOF commented on Source/AppleLogger/LogService.swift
> +    public func log(_ message: StaticString, log: OSLog?, type: OSLogType, _ args: CVarArg) {
다른 comment 처리로 OSLog 를 non null type 으로 만들어 아래 복잡한 if else 로직을 제거할 수 있다고 생각합니다.

2022-10-12 08:10 UTC, enebin commented on Source/AppleLogger/LoggerExtension.swift
> +    public func configure(with setting: Setting) {
그 경우 `setLogLevel`은 상관 없이 유지 하나요??

2022-10-12 08:48 UTC, 0xWOF commented on Source/AppleLogger/LoggerExtension.swift
> +    public func configure(with setting: Setting) {
넵넵 그래서 setting 은 var 이지만 외부접근이 불가능하고, logLevel 만 setter 를 통해 수정가능하게요.

2022-10-13 07:17 UTC, enebin commented on Source/AppleLogger/LoggerExtension.swift
> +    public var setting: Setting {
Logger 세팅 확인하면서 디버깅 용도로 사용할 수도 있을 것 같은데 혹시 그런 면에서는 어떻게 생각하시나요?
지금이야 설정이 몇 개 없어서 괜찮은데 나중에 많아지면 헷갈릴 수도 있을 것 같아서요.
`loggerSetting`이 internal이기 때문에 이 변수가 없으면 별달리 확인할 방법이 없습니다.

ex) 현재 로거의 `usePrint` 설정 or 로그 레벨을 확인 -> `print(logger.setting.logLevel)`

2022-10-13 07:29 UTC, enebin commented on Source/AppleLogger/LoggerExtension.swift
> +    public func configure(with setting: Setting) {
그런데 이 경우 모든 가변 프로퍼티에 세터를 만들어주어야 할 것 같은데 괜찮을까요?

`configure`를 만들었던 이유도 그것 같은데 현재 setting에 직접 접근할 수 있는 방법이 없어서요.
이 방식이면 `setUsePrint`도 만들어야 되는 게 맞겠네요.

2022-10-13 09:13 UTC, 0xWOF commented on Source/AppleLogger/LoggerExtension.swift
> +    public func configure(with setting: Setting) {
저는 usePrint 를 logger 사용 도중에 변경할 수 없게 해야 한다고 생각합니다. 그래서 init 시에 setting 을 입력하는 것으로 usePrint 를 설정하고 이후에는 수정 할 수 없도록이요. 그럼 setUsePrint 는 usePrint 를 logger 사용 도중에 변경하는 함수이니 만들어낼 필요가 없지요.

2022-10-13 09:14 UTC, 0xWOF commented on Source/AppleLogger/LoggerExtension.swift
> +    public var setting: Setting {
그렇다면 제공하는것도 괜찮다고 생각합니다. 다시 생각해보니 Setting 은 Value 타입이니 사용도중 logger 의 setting 의 수정할 수 없겠네요.

2022-10-14 06:32 UTC, 0xWOF approved these changes

2022-10-14 06:34 UTC, merged