feature: Add Array Storage Manager(CoreData, File)
ab180/saby pull request #5
Opened 2022-11-17 02:03 UTC by minjae999

2022-11-17 02:04 UTC, minjae999 commented
기본적인 틀은 완성했습니다. 수정했으면 하는곳이 있다면 확인 해 주세요.

2022-11-22 04:48 UTC, 0xWOF requested changes
몇가지 주요하지 않은점만 수정해주시면 될 것 같습니다!

2022-11-22 04:48 UTC, 0xWOF commented on Test/AppleStorage/FileArrayStorageTests.swift
> +        storage.save().then {
비슷하게 여기도 이렇게 개선가능할 듯 합니다.
```swift
Promise {
    return storage.save()    
}.then {
    return storage.get(limit: .unlimited)
}.then {
    $0[0 ... testItems.removeCount - 1].forEach(storage.delete)

    return storage.save()
}.then {
    return storage.get(limit: .unlimited)
}.then { fetchedItems in
    XCTAssertEqual(fetchedItems.count, testItems.pushCount - testItems.removeCount)
    expectation.fulfill()
}
```

2022-11-22 04:48 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +        NotificationCenter.default.addObserver(
필요없는 코드 아닌가요?

2022-11-22 04:48 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    let rawObjectPointer: CoreDataFetchPointer
`raw` 라는 접두사가 필요한 이유가 무엇인가요? `UnsafeRawPointer` 일 거 같은 느낌이 들어서 굳이 필요없다면 없애는 것이 좋아보입니다.

2022-11-22 04:48 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +public struct CoreDataFetchPointer {
`UnsafeRawPointer` 를 연상시켜서 `CoreDataModelDescriptor` 정도가 어떨까요?

2022-11-22 04:48 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +        Promise(on: .main) { self }
왜 `.main` 이 필요한 것인가요? 특별한 이유가 없다면 `.global()` 이 좋아 보입니다.

2022-11-22 04:48 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +            return Promise { Array(capturedItems[0 ..< min]) }
이 경우, `Promise.resolved()` 를 사용하시는 것이 lambda 실행을 하지 않아서 성능적으로 더 좋을 듯 합니다.

2022-11-22 04:48 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +            self.locker.lock()
`defer { self.locker.unlock() }` 을 사용할 경우, throw 에 대한 unlock 로직을 제거할 수 있어서 더 간결한 코드를 작성할 수 있을 것 같습니다.

2022-11-22 04:48 UTC, 0xWOF commented on Test/AppleStorage/CoreDataArrayStorage.swift
> +    @nonobjc class func fetchRequest() -> NSFetchRequest<TestItem> {
`@something` 다음에 개행문자를 추가해주세요! (코딩스타일가이드에 추가하겠습니다.)

2022-12-01 01:07 UTC, minjae999 commented on Test/AppleStorage/CoreDataArrayStorage.swift
> +        CoreDataArrayStorageTests.storage.then { storage in
MainThread에서 생성되는 CoreData Context를 Global Queue에 밀어넣는 방식으로 Chaining을 진행하도록 변경하도록 함.
> MainThread에서 Then Chaining을 진행했을 경우에 Deadlock으로 인해 해당 구현으로 작성됨.

2022-12-01 01:08 UTC, minjae999 commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +public struct CoreDataFetchPointer {
기가막힌 생각입니다.

2022-12-01 01:29 UTC, minjae999 commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +            return Promise { Array(capturedItems[0 ..< min]) }
해당 부분은 `Promise { resolve, reject in Array(cap ... } `
요 방식으로 가라는건가요?

To. @0xWOF

2022-12-01 01:33 UTC, minjae999 commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +            self.locker.lock()
final로 대체, Promise에 대한 defer동작이 원하는대로 동작하지 않음. 
```
Promise {
    self.locker.lock()
    defer { self.locker.unlock() }
    ...
```

2022-12-01 01:37 UTC, minjae999 commented
Rebased to origin/main

2022-12-01 02:13 UTC, minjae999 commented
Rebased to origin/main
[6282cb7](https://github.com/ab180/saby/pull/5/commits/6282cb7d3e4c044ab2bf1fde10a4ab0b1151c3c6) 이하 신규 변경

2022-12-01 02:37 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +            return Promise { Array(capturedItems[0 ..< min]) }
이렇게 코드가 변경되는 것이 더 좋아보여서 의견드린 것 입니다!
`return Promise { Array(capturedItems[0 ..< min]) }`
=> `return Promise.resolved(Array(capturedItems[0 ..< min]))`

2022-12-01 04:44 UTC, minjae999 commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +            return Promise { Array(capturedItems[0 ..< min]) }
아하 그렇게도 쓸 수 있군요 해당 사항 변경 및 반영하도록 할게요.

2022-12-01 08:28 UTC, 0xWOF requested changes
수정 부탁드립니다!

2022-12-01 08:28 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    var storages: [String: any ArrayStorage] = [:]
https://forums.swift.org/t/se-0353-constrained-existential-types/56853/21

이 문법 하위지원 안되는걸로 아는데 아닐까요? fileprivate 라 그냥 CoreDataArrayStorage 를 써도 될 듯 합니다.

2022-12-01 08:28 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +            CoreDataContextManager.shared.locker.unlock()
then 과 finally 는 서로 다른 thread 에서 동작할 수 있습니다. 그러므로 unlock 을 finally 에서 하는걸 데드락의 원인이 될 수 있습니다. unlock 을 then 에서 처리해주세요.

2022-12-01 08:28 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +fileprivate final class CoreDataContextManager {
이 공유 저장소가 왜 필요한 건가요?

2022-12-01 08:28 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    public class func create(objectPointer: CoreDataModelDescriptor, entityKeyName: String) -> Promise<CoreDataArrayStorage> {
objectPointer 이름이 modelDescriptor 되어야 할 듯 하네요.

2022-12-01 08:28 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    public class func create(objectPointer: CoreDataModelDescriptor, entityKeyName: String) -> Promise<CoreDataArrayStorage> {
지금 이 함수는 model 파일이 bundle 에 resource 로 있어야만 사용가능합니다.

그런데 airbridge ios sdk 는 static framework 될 것을 목표하고 있어서 resource 사용이 불가능합니다. (dynamic framework 만 resource 사용가능) 그런데 사실 코드를 통해 nsmanagedobjectmodel 을 생성하는것이 가능합니다. 그러므로 descriptor 말고 nsmanagedobjectmodel 을 바로 입력받는 함수도 있어야 합니다.

참고: https://tigi44.github.io/ios/iOS,-Swift-Core-Data-Model-in-a-Swift-Package/

2022-12-01 08:28 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +            CoreDataContextManager.shared.locker.unlock()
위와 동일

2022-12-01 08:28 UTC, 0xWOF commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +        return directoryPath.appendingPathComponent(String(describing: Item.self))
파일이름을 클래스명으로 지정하는게 아니라 파일명을 입력받을 수 있었으면 합니다. 동일한 Type 타입으로 여러 파일을 저장할 수 있도록이요.

2022-12-02 00:16 UTC, minjae999 commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +            CoreDataContextManager.shared.locker.unlock()
같은 Then일 필요는 없나요? Chaining된 Then에서 Unlock해도 상관이 없나요?

2022-12-02 00:39 UTC, minjae999 commented on Source/AppleStorage/Protocol/FileArrayStorage.swift
> +        return directoryPath.appendingPathComponent(String(describing: Item.self))
아예 폴더 이름까지 받도록 강제해버렸습니다.

2022-12-02 01:15 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +            CoreDataContextManager.shared.locker.unlock()
저는 같은 then 을 의미했습니다! 물론 queue 가 concurrent queue 라면 위 코드는 정상동작할 것입니다. 하지만 serial queue 일 때 정상동작을 보장할 수가 없고, finally 가 꼭 필요하지 않다고 생각해서 위 의견 드렸습니다. (defer 사용시 에러가 발생해도 unlock 하는 것이 가능)

2022-12-02 01:57 UTC, minjae999 commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +fileprivate final class CoreDataContextManager {
Class Method에서 접근할 변수를 사용하기 위함입니다. Generic은 static method를 선언하지 못하기에 해당 부분은 그렇게 구현했습니다. 다른 좋은 생각이 있을까요?

2022-12-02 03:17 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +fileprivate final class CoreDataContextManager {
loadPersistentStore 가 중복으로 호출되면 안되기 때문, 하지만 deinit 시에 storage 에서 제거하는 로직은 필요함

2022-12-02 04:54 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    var storages: [String: any ArrayStorage] = [:]
iOS 11 에뮬레이터에서 정상동작한다면 상관 없습니다.

2022-12-02 05:59 UTC, minjae999 commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    var storages: [String: any ArrayStorage] = [:]
iOS 11 빌드 확인했습니다. 실행은 Simulator 16.1입니다. 필요하다면 13.x버전으로 낮춰서 해볼 수 있습니다.

2022-12-02 06:39 UTC, minjae999 commented
Rebased: 559e1ee509a9d6f60ca731280a23ede7249b3d89

2022-12-02 06:40 UTC, minjae999 commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +            CoreDataContextManager.shared.locker.unlock()
global을 명시함, 가독성 및 유지보수 향상을 위해 finally 를 유지 & then chaning을 위함.

2022-12-02 06:41 UTC, minjae999 commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    public class func create(objectPointer: CoreDataModelDescriptor, entityKeyName: String) -> Promise<CoreDataArrayStorage> {
해당 새로운 케이스 메소드 추가 및, 테스트 케이스 추가 됨. 
> CoreDataModelDescriptor를 제거하고 파라미터를 풀어서 받도록 변경함

2022-12-02 08:13 UTC, 0xWOF commented on Source/AppleStorage/Protocol/CoreDataArrayStorage.swift
> +    var storages: [String: any ArrayStorage] = [:]
13.x 로 한번만 테스트 진행 부탁드립니다!

2022-12-02 08:18 UTC, 0xWOF requested changes
진짜 마이너한 부분만 수정 부탁드릴게요!

2022-12-02 08:18 UTC, 0xWOF commented on Test/AppleStorage/CoreDataArrayStorageManualTests.swift
> +    func testManagingProgramically() {
이거 CoreDataArrayStorageTests 에 포함될 수 있지 않나요? 케이스가 좀 더 많아지면 분리하는것이 ㅇ떨까요?

2022-12-02 08:18 UTC, 0xWOF commented on Test/AppleStorage/CoreDataArrayStorageTests.swift
> +//  CoreDataArrayStorage.swift
변경 부탁드립니다.

2022-12-02 08:18 UTC, 0xWOF commented on Test/AppleStorage/FileArrayStorageTests.swift
> +final class FileArrayStorageTests: XCTestCase {
위와 동일

2022-12-06 08:56 UTC, minjae999 commented on Test/AppleStorage/CoreDataArrayStorageManualTests.swift
> +    func testManagingProgramically() {
기존 CoreData는 Coredata Model과 충돌이 있어(Context생성 불가) 둘 중 하나의 방식만 사용가능하여 두개를 분리시켰습니다.
1. Modeler를 사용하여 구현하는 방식
2. Modeler를 제외하여 코드 방식으로 생성하는 방식

2022-12-09 02:06 UTC, minjae999 commented on Test/AppleStorage/CoreDataArrayStorageManualTests.swift
> +    func testManagingProgramically() {
호달달.. 파일위치가 같이 있으면 안되네요, class가 달라두요..

2022-12-09 02:11 UTC, minjae999 commented on Test/AppleStorage/CoreDataArrayStorageManualTests.swift
> +    func testManagingProgramically() {
이게 문제가 있습니다. 
전체 테스트를 돌리면 하나의 Module에서 여러개가 올라가 테스트 하는 방식인가본데요, 

CoreDataArrayStorage와 CoreDataArrayStorageManual 테스트를 동시에 진행 할 수 없습니다. 
두개를 한꺼번에 돌리니 오류가 나네요, 각자 돌렸을 경우에는 문제가 없구요. 

따라서 CoreDataArrayStorageManual를 주석처리하고 테스트 대상은 CoreDataArrayStorage로만 하고자 합니다. 

```
error: No NSEntityDescriptions in any model claim the NSManagedObject subclass 'TestItem' so +entity is confused.  Have you loaded your NSManagedObjectModel yet ?
CoreData: error: No NSEntityDescriptions in any model claim the NSManagedObject subclass 'TestItem' so +entity is confused.  Have you loaded your NSManagedObjectModel yet ?
```
```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSFetchRequest could not locate an NSEntityDescription for entity name 'TestItem''
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018040e7ec __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180051144 objc_exception_throw + 56
	2   CoreData                            0x00000001844ffda8 -[NSFetchRequest(_NSInternalMethods) _incrementInUseCounter] + 0
	3   CoreData                            0x000000018452106c -[NSManagedObjectContext executeRequest:error:] + 164
...
```

2022-12-09 03:12 UTC, 0xWOF requested changes
1. 테스트코드 실패한 것 해결해주세요.
2. Manual 과 로딩을 모두 테스트할 수 없다면 Manual 만 테스트해주시는게 더 좋을 것 같습니다.

2023-01-17 01:46 UTC, minjae999 commented
SabyAppleStorage에 Async를 지원하고 싶었으나,,, `loadPersistentStores` 를 Async로 지원하지 않네요.. 
언젠가 하는 것으로...

2023-01-17 01:57 UTC, 0xWOF requested changes

2023-01-17 01:57 UTC, 0xWOF commented on Test/AppleStorage/CoreDataArrayStorageTests.swift
> +////
주석 처리하실 것이라면 파일 삭제 부탁드립니다.

2023-01-17 02:57 UTC, 0xWOF approved these changes

2023-01-17 02:57 UTC, merged