feature: implement file dictioanry
ab180/saby pull request #7
Opened 2023-01-20 02:20 UTC by minjae999

2023-01-20 03:44 UTC, minjae999 commented
- [ ] if문 code convention 정리

- [ ] get문 Promise로 변경

2023-01-20 04:44 UTC, 0xWOF requested changes

2023-01-20 04:44 UTC, 0xWOF commented on Source/AppleStorage/Implement/FileDictionaryStorage.swift
> +        locker.lock()
cachedItems 가 이미 atomic 하기 때문에 lock 이 필요 없어 보입니다.

2023-01-20 04:44 UTC, 0xWOF commented on Source/AppleStorage/Implement/FileDictionaryStorage.swift
> +        locker.lock()
cachedItems 가 이미 atomic 하기 때문에 lock 이 필요 없어 보입니다.

2023-01-20 04:44 UTC, 0xWOF commented on Source/AppleStorage/Implement/FileDictionaryStorage.swift
> +    private func fetchFromFiles() -> [Key: Value] {
file 이 하나인데 왜 files 인가요?

2023-01-20 04:44 UTC, 0xWOF commented on Source/AppleStorage/Implement/FileDictionaryStorage.swift
> +    func removeAll() {
test 를 위한 함수인 것으로 보입니다. 그렇다면 Test 파일에서 구현하는것이 맞는것 같습니다.

2023-01-20 04:44 UTC, 0xWOF commented on Test/AppleStorage/FileDictionaryStorageTests.swift
> +final class FileDictionaryStorageTests: XCTestCase {
`Tests` => `Test` 로 변경 부탁드립니다. (Convention)

2023-01-20 04:44 UTC, 0xWOF commented on Source/AppleStorage/Implement/FileDictionaryStorage.swift
> +            self.locker.lock()
이건 cacheItems 가 아닌, file 에 대한 lock 으로 필요할 것 같습니다. 👍

2023-01-26 00:50 UTC, minjae999 commented on Source/AppleStorage/Implement/FileDictionaryStorage.swift
> +            self.locker.lock()
Locking범위를 다음과 같이 조절
- Create Directory
- Write to File

2023-01-26 01:09 UTC, 0xWOF requested changes

2023-01-26 01:09 UTC, 0xWOF commented on Source/AppleStorage/Implement/FileDictionaryStorage.swift
> +            return
굳이 작성할 필요 없어 보입니다.

2023-01-26 01:09 UTC, 0xWOF commented on Source/AppleStorage/Implement/FileDictionaryStorage.swift
> +            self.locker.unlock()
defer 로 처리하는건 어떨까요?

2023-01-26 01:29 UTC, minjae999 commented on Source/AppleStorage/Implement/FileDictionaryStorage.swift
> +            self.locker.unlock()
작성할 필요가 없다면 빼버리는게 나을 것 같아요. 대신 테스트를 추가하겠습니다.

2023-01-26 02:11 UTC, 0xWOF commented on Source/AppleStorage/Implement/FileDictionaryStorage.swift
> +            self.locker.unlock()
파일 저장에 있어서는 필요한 것 아닌가요? 위의 필요없음은 `return` 을 말하는 것이였습니다.

2023-01-31 06:51 UTC, 0xWOF approved these changes

2023-01-31 06:51 UTC, merged